export const TOGGLE_FLAG = 'TOGGLE_FLAG'
export const INIT = 'INIT'
export const GAME_OVER = 'GAME_OVER'
export const CLEAR = 'CLEAR'
export const SAVE = 'SAVE'
export const RESUME = 'RESUME'
export const GAME_PARAMS = 'GAME_PARAMS'
